### ISSUE TITLE
Support for Pi-hole version 5

### ISSUE THREAD

**Issue by JavanXD** [koljah-de/pi-hole-adlists-updater#1]
I came across your Pi-Hole Updater after I just uploaded mine and added the GitHub tags.

Pihole has changed a lot in its structure since version 5.0. There is no longer the adlists.list. Instead you have to work with the sqlite3 db gravity now.

I have already written an updater for Pi Hole version 5. Have a look at it here: 
https://github.com/JavanXD/ya-pihole-list

I am happy about feedback.

**Comment by koljah-de** [comment]
Thanks for the advice. I've updated the script. Now it works with Pi-hole 5.0 and behaves the same as before.

Sincerely yours
koljah
